### ISSUE TITLE
모바일 페이지에서 Navigation bar toggle버튼 누르면 열리기만 하고 닫히지 않는 문제

### ISSUE THREAD

**Issue by hgkim100** [shipowner99/Tindog#4]
아래 이미지같이 Toggle 버튼을 누르면 메뉴가 내려오는데 다시 누르면 나온 메뉴가 안사라져요

![Screenshot_20230311_190030_Chrome](https://user-images.githubusercontent.com/31885405/224478745-3fd85322-c0f8-45aa-9ded-2302162b7efe.jpg)

**Comment by shipowner99** [comment]
1. 문제:  [navbar toggle 이 열리기만 하고 닫히지 않는다.](https://www.youtube.com/watch?v=zigBDPYIHc8)
![image](https://user-images.githubusercontent.com/120784842/224624261-1f40360f-5188-42a6-a936-254be385c0b6.png)
2. 원인:  bootstrap5에서는 popper 이 이미 포함되었기 때문에 스크립트 한 개만 불러오면 되는데, 강의 보고 이전 버전대로 따라하다가 popper.js 코드와 bootstrap.js 코드를 둘 다 불러와 연결함.
3. 해결방안 : popper.js 코드를 지우고 bootstrap.js 코드만 남기기
4. [결과 및 해결한 커밋: ](https://github.com/shipowner99/Tindog/commit/73958c17e5c90047eaaf4a6ad1e1ede3b74f9840)
![image](https://user-images.githubusercontent.com/120784842/224624299-b57a6a48-a3d9-4c02-b22a-97228417547c.png)
5. 알게된 점: bootstrap docs을 볼 때는 최신 버전인지 확인하자. 주소창에 bootstraop docs 라고 치지 말고 getbootstrap.com 을 쳐서 최신 버전에 들어가자
why? 구글링해서 들어가면 이전 버전이 표시되는 경우가 많다.
